config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :categories, only: [:show] do
    resources :products, only:[ :show]
  end

  get    '/sign_up'           => 'users#new'
  post   '/sign_up'           => 'users#create'

  get    '/sign_in'           => 'sessions#new'
  post   '/sign_in'           => 'sessions#create'
  delete '/logout'            => 'sessions#destroy'

  post '/cart_item' => 'cart_items#create'
  delete '/cart_item/:cart_item_id' => 'cart_items#destroy', as: :delete_cart_item

  get '/cart' => 'carts#show'
  delete '/cart/:cart_id' => 'carts#destroy', as: :delete_cart
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :orders, only: [:create, :show, :index ]
  resources :account_activations, only: [:edit]

  namespace :admin do
    resources :brands, only: [:new, :create]
    resources :dashboard, only: [:index]
    resources :users, except: [:show]
    post '/promote' => 'users#promote'
    post '/demote'  => 'users#demote'
    resources :categories, except: [:show]
    resources :products
    resources :orders, only: [:index, :show]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :categories, only: [:index, :show] do
        resources :products, only: [ :index ] do
          resources :product_variants
        end
      end
      get    '/products/:product_id' => 'products#show_product'
      
      get    'cart/:cart_id/count'   => 'carts#count'
      get    '/cart/:cart_id'        => 'carts#index'
      post   '/cart/add'             => 'carts#add'
      post   '/cart/buy'             => 'orders#create'

      delete   '/cart'     => 'carts#destroy'

      post   '/sign_up'  => 'users#create'
      post   '/sign_in'  => 'sessions#create'
      delete '/logout'   => 'sessions#destroy'

    end
  end

  match '/api/v1/*path', to: 'api#no_endpoint', via: :all
  
  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController

  def index
    @categories = Category.all
    @product_variants = ProductVariant.all
    @users = User.all
  end
end

app/views/admin/dashboard/_admin_navbar.html.erb
<div class='row'>
	<div id='dashboard-title'>
		<ul class='list-inline'>
			<%= render 'admin/dashboard/navbar/links' %>
		</ul>
	</div>
</div>

app/views/admin/dashboard/index.html.erb
<% content_for :admin_navbar, render('admin/dashboard/admin_navbar') %>
<div id='dashboard-container' class='row' style='text-align: center'>
	<div class='col-md-4' style='padding-left: 0px'>
		<%= link_to admin_categories_path do %>
			<div class='col-md-12'>
		     <p><%= @categories.count %></p>
		     <p class='small-text'>kategorija</p>
			</div>
		<% end %>	
		<div class='col-md-6 col-md-offset-3'>
			<%= link_to 'DODAJ KATEGORIJU', new_admin_category_path %>
		</div>
	</div>

	<div class='col-md-4'>
		<%= link_to admin_products_path do %>
			<div class='col-md-12'>
		     <p><%= @product_variants.count %></p>
		     <p class='small-text'>obuća</p>
			</div>
		<% end %>	
		<div class='col-md-6 col-md-offset-3'>
			<%= link_to 'DODAJ OBUĆU', new_admin_product_path %>
		</div>
	</div>

	<div class='col-md-4' style='padding-right: 0px'>
		<%= link_to admin_users_path do %>
			<div class='col-md-12'>
		    <p><%= @users.count %></p>
		    <p class='small-text'>korisnici</p>
			</div>
		<% end %>	
		<div class='col-md-6 col-md-offset-3'>
			<%= link_to 'DODAJ KORISNIKE', new_admin_user_path %>
		</div>
	</div>
</div>
<script>
$(document).ready(function() {
    $('#dashboard-title').find('a').each(function() {
    if (this.href == window.location.href) {
        $(this).addClass('active-link')
        }
    });
});
</script>