config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :categories, only: [:show] do
    resources :products, only:[ :show]
  end

  get    '/sign_up'           => 'users#new'
  post   '/sign_up'           => 'users#create'

  get    '/sign_in'           => 'sessions#new'
  post   '/sign_in'           => 'sessions#create'
  delete '/logout'            => 'sessions#destroy'

  post '/cart_item' => 'cart_items#create'
  delete '/cart_item/:cart_item_id' => 'cart_items#destroy', as: :delete_cart_item

  get '/cart' => 'carts#show'
  delete '/cart/:cart_id' => 'carts#destroy', as: :delete_cart
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :orders, only: [:create, :show, :index ]
  resources :account_activations, only: [:edit]

  namespace :admin do
    resources :brands, only: [:new, :create]
    resources :dashboard, only: [:index]
    resources :users, except: [:show]
    post '/promote' => 'users#promote'
    post '/demote'  => 'users#demote'
    resources :categories, except: [:show]
    resources :products
    resources :orders, only: [:index, :show]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :categories, only: [:index, :show] do
        resources :products, only: [ :index ] do
          resources :product_variants
        end
      end
      get    '/products/:product_id' => 'products#show_product'
      
      get    'cart/:cart_id/count'   => 'carts#count'
      get    '/cart/:cart_id'        => 'carts#index'
      post   '/cart/add'             => 'carts#add'
      post   '/cart/buy'             => 'orders#create'

      delete   '/cart'     => 'carts#destroy'

      post   '/sign_up'  => 'users#create'
      post   '/sign_in'  => 'sessions#create'
      delete '/logout'   => 'sessions#destroy'

    end
  end

  match '/api/v1/*path', to: 'api#no_endpoint', via: :all
  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @products = Product.products_without_discount
    @sale_products = Product.products_with_discount
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_navbar.html.erb
<div style='width: 100%; height: 400px;' class='cover-image'>
  
  <nav class="navbar navbar-cover">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'abhShoes', root_path, class: "navbar-brand" %>
      </div>
      <div class='collapse navbar-collapse'>
        <ul class="nav navbar-nav navbar-midle">
          <% Category.all.each do |category| %>
            <li><%= link_to category.title, category_path(category) %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <% if current_user.role == 'admin' %>
              <li><%= link_to 'ADMIN', admin_dashboard_index_path %>
            <% end %>

            <% if current_cart.cart_items.blank? %>

              <li><%= link_to "<span class='glyphicon glyphicon-shopping-cart'></span>".html_safe, '#', id: 'navbar-empty-cart' %></li>
            <% else %> 

              <li><%= link_to "<span class='glyphicon glyphicon-shopping-cart'>
                <span class='number-notification'>#{current_cart.count_items}</span>
                </span>".html_safe, cart_path %>
              </li>
            <% end %>
            <% if current_user.orders.blank? %>
              <li id='all-orders-title'>NEMA NARUDZBI</li>
            <% else %>
              <li><%= link_to 'NARUDZBE', orders_path %></li>
            <% end %>
            <li><%= link_to 'LOG OUT', logout_path, method: 'delete' %></li>
          <% else %>
          <% if current_cart.cart_items.blank? %>
            <li><%= link_to "<span class='glyphicon glyphicon-shopping-cart'></span>".html_safe, '#', id: 'navbar-empty-cart' %></li>
          <% else %> 
            <li><%= link_to "<span class='glyphicon glyphicon-shopping-cart'>
              <span class='number-notification'>#{current_cart.count_items}</span>
              </span>".html_safe, cart_path %>
            </li>
          <% end %>
            <li><%= link_to 'LOGIN', sign_in_path %></li>
            <li><%= link_to 'REGISTER', sign_up_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/welcome/_popular.html.erb
<div class='row'>
<span>POPULARNO</span>
</div>
<div class='row'>
  <div id="popularno-carousel" class="carousel slide" data-ride="carousel" data-interval="false">
    <div class="carousel-inner" role="listbox">
      <% if @products.length <= 4 %>
        <div class="item active">
          <% @products.each do |product| %>
            <% if product.categories.blank? %>
              <% next %>
            <% else %>
              <%= render 'welcome/carousel/carousel_popular', f: product %>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <% @products.each_slice(4) do |slice| %>
          <% if @products.slice(0..3) == slice %>
            <div class="item active">
              <% slice.each do |product| %>
                <% if product.categories.blank? %>
                  <% next %>
                <% else %>
                  <%= render 'welcome/carousel/carousel_popular', f: product %>
                <% end %>
              <% end %>
            </div>
          <% else %>
            <div class="item">
              <% slice.each do |product| %>
                <% if product.categories.blank? %>
                  <% next %>
                <% else %>
                  <%= render 'welcome/carousel/carousel_popular', f: product %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
        <a class="left carousel-control" href="#popularno-carousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#popularno-carousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/_popularno.html.erb
<div class='row'>
  <span>POPULARNO</span>
  <div class='pull-right'>
    <span style='margin-right: 10px'>PRETRAZI</span>
    <span class='glyphicon glyphicon-search'></span>
  </div>
  </div>
  <div class='row'>
    <div id="popularno-carousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <% if @products.length <= 4 %>
          <div class="item active">
            <% @products.each do |product| %>
              <div class="col-sm-6 col-md-3">
                <div class="thumbnail">
                  <img src="<%= product.photo_url %>" alt="...">
                  <div class="caption">
                    <h4><%= product.title %></h3>
                    <p><%= product.price %>KM</p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
          <% @products.each_slice(4) do |slice| %>
            <% if @products.slice(0..3) == slice %>
              <div class="item active">
                <% slice.each do |product| %>
                  <div class="col-sm-6 col-md-3">
                    <div class="thumbnail">
                      <img src="<%= product.photo_url %>" alt="...">
                      <div class="caption">
                        <h4><%= product.title %></h3>
                        <p><%= product.price %>KM</p>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% else %>
              <div class="item">
                <% slice.each do |product| %>
                    <div class="col-sm-6 col-md-3">
                      <div class="thumbnail">
                        <img src="<%= product.photo_url %>" alt="...">
                        <div class="caption">
                          <h4><%= product.title %></h3>
                          <p><%= product.price %>KM</p>
                        </div>
                      </div>
                    </div>
                <% end %>
              </div>  
            <% end %>
          <% end %>
          <a class="left carousel-control" href="#popularno-carousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#popularno-carousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        <% end %>
      </div>
    </div>
  </div>

app/views/welcome/_sale.html.erb
<div class='row'>
<span>SALE</span>
</div>
<div class='row'>
  <div id="sale-carousel" class="carousel slide" data-ride="carousel" data-interval="false">
    <div class="carousel-inner" role="listbox">
      <% if @products.length <= 4 %>
        <div class="item active">
          <% @products.each do |product| %>
            <% if product.categories.blank? %>
              <% next %>
            <% else %>
              <%= render 'welcome/carousel/carousel_sale', f: product %>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <% @sale_products.each_slice(4) do |slice| %>
          <% if @sale_products.slice(0..3) == slice %>
            <div class="item active">
              <% slice.each do |product| %>
                <% if product.categories.blank? %>
                  <% next %>
                <% else %>
                  <%= render 'welcome/carousel/carousel_sale', f: product %>
                <% end %>
              <% end %>
            </div>
          <% else %>
            <div class="item">
              <% slice.each do |product| %>
                <%= render 'welcome/carousel/carousel_sale', f: product %>
              <% end %>
            </div>  
          <% end %>
        <% end %>
        <a class="left carousel-control" href="#sale-carousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#sale-carousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% content_for :nav, render('welcome/navbar') %>
<div id='home-screen'>
  <div id='popularno'>
    <%= render 'welcome/popular' %>
  </div>
  <div id='sale'>
    <%= render 'welcome/sale' %>
  </div>
</div>