config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :categories, only: [:show] do
    resources :products, only:[ :show]
  end

  get    '/sign_up'           => 'users#new'
  post   '/sign_up'           => 'users#create'

  get    '/sign_in'           => 'sessions#new'
  post   '/sign_in'           => 'sessions#create'
  delete '/logout'            => 'sessions#destroy'

  post '/cart_item' => 'cart_items#create'
  delete '/cart_item/:cart_item_id' => 'cart_items#destroy', as: :delete_cart_item

  get '/cart' => 'carts#show'
  delete '/cart/:cart_id' => 'carts#destroy', as: :delete_cart
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :orders, only: [:create, :show, :index ]
  resources :account_activations, only: [:edit]

  namespace :admin do
    resources :brands, only: [:new, :create]
    resources :dashboard, only: [:index]
    resources :users, except: [:show]
    post '/promote' => 'users#promote'
    post '/demote'  => 'users#demote'
    resources :categories, except: [:show]
    resources :products
    resources :orders, only: [:index, :show]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :categories, only: [:index, :show] do
        resources :products, only: [ :index ] do
          resources :product_variants
        end
      end
      get    '/products/:product_id' => 'products#show_product'
      
      get    'cart/:cart_id/count'   => 'carts#count'
      get    '/cart/:cart_id'        => 'carts#index'
      post   '/cart/add'             => 'carts#add'
      post   '/cart/buy'             => 'orders#create'

      delete   '/cart'     => 'carts#destroy'

      post   '/sign_up'  => 'users#create'
      post   '/sign_in'  => 'sessions#create'
      delete '/logout'   => 'sessions#destroy'

    end
  end

  match '/api/v1/*path', to: 'api#no_endpoint', via: :all
  
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_one :order
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  def total
    price = []
    cart_items.each do|item|
      product = item.product_variant.product
      if product.has_discount?
        price << product.with_discount * item.quantity
      else
        price << product.price * item.quantity 
      end
    end
    return price.inject(:+)
  end

  def delivery_cost
    how_many_orders * 5
  end

  def how_many_orders
    orders = []
    cart_items.each do|item|
      orders << item.quantity
    end
    return orders.inject(:+)
  end

  def total_with_delivery
    total + delivery_cost
  end

  def new_item(option = {})
    current_item = cart_items.find_by(product_variant_id: option[:product_variant].id)
    
    if !current_item
      current_item = option[:product_variant].cart_items.build(option[:params])
    else
      option[:params][:quantity].empty? ? current_item.quantity = nil : current_item.quantity += option[:params][:quantity].to_i
    end
    current_item
    #byebug
  end

 
  
  def remove_product_variant
    cart_items.each do |item|
      product_variant = ProductVariant.find(item.product_variant_id)
      new_quantity = product_variant.quantity - item.quantity
      product_variant.update_attribute(:quantity, new_quantity)
      product_variant.destroy if product_variant.quantity == 0 
    end
  end

  def check_items_quantity
    self.cart_items do |item|
      return nil if item.quantity > ProductVariant.find(item.product_variant_id)
    end
  end

  def has_cart_items?
    return true if Cart.find_last(self.id).cart_items.present?
  end

   def add_user_id(current_user)
    self.update_attribute(:user_id, current_user.id)
  end

  def no_user?
    self.user_id.blank?
  end

  def self.find_unfinished_cart(user)
    self.find_by(user_id: user.id, finished: false)
  end

  def count_items
    self.cart_items.map { |x| x.quantity}.inject(0, :+)
  end

 
  private
  
  def self.find_last(id)
    self.where(user_id: id).last
  end
end

app/controllers/api/v1/carts_controller.rb
class Api::V1::CartsController < ApiController

  def index
    if params[:api_token]
      user = User.find_by(api_token: params[:api_token])
      current_cart = user.cart
      @cart_items = current_cart.cart_items
      render response: @cart_items.as_json
    else
      current_cart = Cart.find(params[:cart_id])
      @cart_items = current_cart.cart_items
      render response: @cart_items.as_json
    end
    rescue ActiveRecord::RecordNotFound
    raise Api::Exceptions::RecordNotFound, 'Cart'
  end

  def add
    @product = params[:product_id]
    begin
    if params[:api_token]
      user = User.find_by(api_token: params[:api_token])
      current_cart = Cart.find_by(user_id: user.id)
      if current_cart
        current_cart
      else
        current_cart = user.create_cart
      end
    elsif params[:cart_id]
      current_cart = Cart.find(params[:cart_id])
    else
      current_cart = Cart.create
    end
    rescue Exceptions => e
      puts e
    end
    
    size = Size.find_by(product_size: params[:size_id])

    @product_variant = ProductVariant.find_by(size_id:  size.id, 
                                              color_id: Color.find_by(hex_value: params[:color_id]),
                                              product_id: @product)
    
    @cart_item = current_cart.new_item(product_variant: @product_variant, 
                                       params: {'cart_id': current_cart.id, 'quantity': params[:quantity] })
   
    if @cart_item.save
      render response: @cart_item.as_json
    else
      raise Api::Exceptions::ValidationException.new(@cart_item.errors.full_messages)
    end
  end

  def destroy
    if params[:api_token]
      user = User.find_by(:api_token)
      cart = user.cart
      cart.cart_items.find(params[:cart_item_id]).destroy
      if cart.cart_items.blank?
        cart.destroy
        render response: { cart_id: nil }
      else 
        render response: cart.cart_items.as_json 
      end
    else
      cart = Cart.find(params[:cart_id])
      cart.cart_items.find(params[:cart_item_id]).destroy
      if cart.cart_items.blank?
        cart.destroy
        render response: { cart_id: nil }
      else 
        render response: cart.cart_items.as_json 
      end
    end
  end

  def count
    if params[:api_token]
      user = User.find_by(:api_token)
      cart = user.cart
      render response: { 'count': cart.cart_items.map { |x| x.quantity}.inject(0, :+) }
    else
      cart = Cart.find(params[:cart_id])
      render response: { 'count': cart.cart_items.map { |x| x.quantity}.inject(0, :+) }
    end
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :cart_exist?
  
  def show
    @cart = current_cart.cart_items
    @order = Order.new
  end

  def destroy
    Cart.find(params[:cart_id]).destroy
    flash[:success] = 'Your cart is now empty'
    redirect_to root_path
  end

  private

  def cart_exist?
    #byebug
    redirect_to root_path if current_cart.nil? || order_already_completed?
  end

  def order_already_completed?
    if !current_cart.order.nil?
      session[:cart_id] = nil
      true
    end
  end
end

app/helpers/api/v1/carts_helper.rb
module Api::V1::CartsHelper
  def custom_cart_response(current_cart)
    @cart_items = current_cart.cart_items
    render response: @cart_items.as_json
  end
end

app/helpers/carts_helper.rb
module CartsHelper


  def current_cart
    if current_user
      #byebug
      if !current_user.has_cart?
        create_cart
      elsif current_user.has_unfinished_cart?
        current_user.unfinished_cart
      elsif cart_present?
        if @current_cart.no_user?
          @current_cart.add_user_id(current_user)
        else
          create_cart
        end
      end
    else
      if cart_present?
        @current_cart
      else
        create_cart
      end
    end
  end

 
  def create_cart
    if current_user
      @current_cart = current_user.create_cart
    else
      @current_cart = Cart.create
    end
    session[:cart_id] = @current_cart.id
    return @current_cart
  end

  def cart_present?
    @current_cart = Cart.find_by(id: session[:cart_id])
    return @current_cart if @current_cart.present?
  end

  def has_deleted_product_variant?(cart)
    return cart.map { |item| item.product_variant.deleted? }.include? true
  end
  
end

app/views/carts/_cart_items.html.erb
<div class='row'> 
  <div class='col-md-12 space'>
    <%= link_to "<span id='remove-item' class='glyphicon glyphicon-remove'></span>"
      .html_safe, delete_cart_item_path(f.id),  method: :delete, data: { confirm: 'Are you sure?' } %>
    <div id='cart-picture' class='col-md-3'>
      <img src="<%= f.product_variant.product.picture_link %>" width='150' height='auto'>
    </div>
    <div id='product-details' class='col-md-6 cart-details'>
      <p>Model: <%= f.product_variant.product.brand.title %></p>
      <p>Veličina: <%= f.product_variant.size.product_size %></p>
      <p>Boja: <%= f.product_variant.color.product_color %></p>
      <p>ID: <%= f.product_variant.id %></p>
    </div>
    <div id='cart-info' class='col-md-3'>
      <div class="row">
        <div class='pull-right'>
          <p style='margin-bottom: 0px'>Cijena:</p>
          <% if f.product_variant.product.has_discount? %>
            <p><strong><%= number_with_precision(f.product_variant.product.with_discount, precision: 2) %>KM</strong></p>
          <% else %>
            <p><strong><%= number_with_precision(f.product_variant.product.price, precision: 2) %>KM</strong></p>    
          <% end %>      
        </div>
      </div>
      <div class="row">
        <div class='pull-right'>
          <p style='display: inline-block'>Kolicina:</p>
          <div id='quantity-cart'>
            <p><%= f.quantity %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/_deleted_cart_items.html.erb
<div class='row'>
  <div class='col-md-12 space' style='background-color: #fcf8e3'>
    <%= link_to "<span id='remove-item-deleted' class='glyphicon glyphicon-remove'></span>"
      .html_safe, delete_cart_item_path(f.id),  method: :delete, data: { confirm: 'Are you sure?' } %>
    <div id='cart-picture' class='col-md-3'>
      <img src="<%= f.product_variant.product.picture_link %>" width='150' height='auto'>
    </div>
    <div id='product-details' class='col-md-6 cart-details'>
      <div class='deleted-item-message'>
        <p>Proizvod je trenutno nedostupan</p>
      </div>
      <p>Model: <%= f.product_variant.product.brand.title %></p>
      <p>Veličina: <%= f.product_variant.size.product_size %></p>
      <p>Boja: <%= f.product_variant.color.product_color %></p>
      <p>ID: <%= f.product_variant.id %></p>
    </div>
    <div id='cart-info' class='col-md-3'>
      <div class="row">
        <div class='pull-right'>
          <p style='margin-bottom: 0px'>Cijena:</p>
          <p><strong><%= f.product_variant.product.price %>KM</strong></p>
        </div>
      </div>
      <div class="row">
        <div class='pull-right'>
          <p style='display: inline-block'>Kolicina:</p>
          <div id='quantity-cart'>
            <p><%= f.quantity %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
  <div class='col-md-8'>  
    <div class='row' style='margin-bottom: 30px'>
      <h3 style='margin-left: 30px'>Vaša korpa</h3>
    </div>
    <% @cart.each do |cart_item| %>
      <% if cart_item.product_variant.deleted? %>
        <%= render 'carts/deleted_cart_items', f: cart_item %>
      <% else %>
        <%= render 'carts/cart_items', f: cart_item %>
      <% end %>
    <% end %>
  </div>
    <% if has_deleted_product_variant? @cart %>
      <div class='col-md-4'>
        <div class="alert alert-warning" role="alert">
          <strong>Napomena:</strong>
          U korpi se nalazi proizvod koji nije dostupan, i ako zeliti nastaviti kupovinu, izbrisite ga iz korpe.
        </div>
      </div>
    <% else %>

    <div id='order' class='col-md-4'>
      <div class='col-md-10 pull-right' style='margin: 20px 0px; padding: 0px'>
        <ul class="list-inline">
          <li style='margin-right: 75px'>KORPA</li>
        </ul>
      </div>
      <div class='col-md-10 pull-right' style='border: 1px solid #ECDCDC; padding: 0px'>
        <div style='margin: 15px; padding-bottom: 15px; border-bottom: 1px solid #ECDCDC'>
          <div class='row'>
            <div class='col-md-7 pull-left' style='padding: 0px; margin-bottom: 21px'>
              <p>Narudzba <span style='color: #BB9E9E; margin-left: 10px'><%= current_cart.how_many_orders %> proizvoda</span></p>
            </div>
          </div>
          <div class='row'>
            <div class='col-md-5 pull-right' style='text-align: right; padding: 0px'>
              <p>Cijena:</p>
              <p><strong><%= number_with_precision(current_cart.total, precision: 2) %>KM</strong></p>
            </div>
          </div>
          <br>
          <div class='row'>
            <div class='col-md-5 pull-right' style='text-align: right; padding: 0px'>
              <p>Dostava:</p>
              <p><strong><%= number_with_precision(current_cart.delivery_cost, precision: 2) %>KM</strong></p>
            </div>
          </div>
        </div>
        <div class='row'>
          <div class='col-md-6 pull-right' style='text-align: right; margin-bottom: 15px'>
            <p>Ukupno: <strong><%= number_with_precision(current_cart.total_with_delivery, precision: 2) %>KM</strong></p>
          </div>
        </div>
      </div>
      <div class='col-md-10 pull-right' style='margin: 0px; padding: 0px'>
        <div class='pull-right' style='margin-top: 15px'>
          <% if current_user %>                                                     
            <%= form_for @order, url: { action: 'create', controller: 'orders' } do %>
              <%= hidden_field_tag :amount, current_cart.total_with_delivery * 100 %>
              <script 
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-email="<%= current_user.email %>"
                data-label="KUPI"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="AbhShop"
                data-amount="<%= current_cart.total_with_delivery * 100 %>"
                data-locale="auto"
                data-shipping-address='true'>
              </script>
              <%= link_to 'ODUSTANI', delete_cart_path(current_cart.id), method: :delete, class: 'btn btn-primary',
                                                                          id: 'discard',
                                                                       data: { confirm: 'Are you sure?' } %>
            <% end %>
          <% else %>
              
              <%= link_to 'ODUSTANI', delete_cart_path(current_cart.id), method: :delete, class: 'btn btn-primary pull-right',
                                                                          id: 'discard',
                                                                       data: { confirm: 'Are you sure?' } %>
              <button id='cart-warning-button' type="button" class="btn btn-info pull-right disabled">KUPI</button> 
              <div style='text-align: center'>                                                     
                <p class='cart-warning-text'><strong>Napomena:</strong> Morate biti logovani da bi izvrsili placanje.
                  <%= link_to 'Loguj se', sign_in_path %>
                </p>
              </div>  
          <% end %>
        </div>
      </div>
    </div>
    <% end %>