config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :categories, only: [:show] do
    resources :products, only:[ :show]
  end

  get    '/sign_up'           => 'users#new'
  post   '/sign_up'           => 'users#create'

  get    '/sign_in'           => 'sessions#new'
  post   '/sign_in'           => 'sessions#create'
  delete '/logout'            => 'sessions#destroy'

  post '/cart_item' => 'cart_items#create'
  delete '/cart_item/:cart_item_id' => 'cart_items#destroy', as: :delete_cart_item

  get '/cart' => 'carts#show'
  delete '/cart/:cart_id' => 'carts#destroy', as: :delete_cart
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :orders, only: [:create, :show, :index ]
  resources :account_activations, only: [:edit]

  namespace :admin do
    resources :brands, only: [:new, :create]
    resources :dashboard, only: [:index]
    resources :users, except: [:show]
    post '/promote' => 'users#promote'
    post '/demote'  => 'users#demote'
    resources :categories, except: [:show]
    resources :products
    resources :orders, only: [:index, :show]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :categories, only: [:index, :show] do
        resources :products, only: [ :index ] do
          resources :product_variants
        end
      end
      get    '/products/:product_id' => 'products#show_product'
      
      get    'cart/:cart_id/count'   => 'carts#count'
      get    '/cart/:cart_id'        => 'carts#index'
      post   '/cart/add'             => 'carts#add'
      post   '/cart/buy'             => 'orders#create'

      delete   '/cart'     => 'carts#destroy'

      post   '/sign_up'  => 'users#create'
      post   '/sign_in'  => 'sessions#create'
      delete '/logout'   => 'sessions#destroy'

    end
  end

  match '/api/v1/*path', to: 'api#no_endpoint', via: :all
  
  
end

app/models/product.rb
class Product < ActiveRecord::Base

  before_save :round_price

  has_many :product_variants, dependent: :destroy 
  has_many :sizes, through: :product_variants
  has_many :colors, through: :product_variants
  belongs_to :brand
  has_and_belongs_to_many :categories

 
  accepts_nested_attributes_for :product_variants, :allow_destroy => true, :reject_if => :all_blank

  has_attached_file :image, styles: {
    thumb: '100x200>',
    square: '200x200#',
    medium: '300x300>'
  }
  validates :discount, :numericality => { :greater_than_or_equal_to => 0 }
  validates :title, uniqueness: true
  validates :brand_id, :title, :price, :description, presence: true
  validate :category_blank
  validate :duplicate_variant

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :image, :less_than => 1.megabytes

  scope :products_with_discount, -> { where('discount > ?', 0) }
  scope :products_without_discount, -> { where(discount: 0) }
  #validates_associated :product_variants, :message => "Already Taken"
  

  def round_price
    self.price.round(1)  
  end

  def duplicate_variant
    without_quantity = self.product_variants.map do |k| 
      k.attributes.except!('quantity', 
                           'id',
                           'created_at',
                           'updated_at') 
    end
    if without_quantity.length > without_quantity.uniq.length 
      errors.add(:product_variant, 'error: There is at least two variants with same attributes')
    end
  end

  def category_blank
    #byebug
    if self.categories.blank?
      errors.add(:category, 'field cant be empty')
    end
  end

  def capitalize_category
    categories.first.title.mb_chars.downcase.split.collect { |category| category.capitalize.to_s }.join(' ')
  end

  def build_with_category(params)
    return unless params[:category_id].present?
    params[:category_id].map do |id|
      self.categories.push(Category.find(id))
    end 
  end

  def picture_link
    #byebug
    if self.image.url.include?('missing') && self.photo_url.blank?
      'https://s3.eu-central-1.amazonaws.com/abhshopdemo/products/300px-No_image_available.svg.png'
    elsif self.image.url.include? 'missing'
      self.photo_url
    else
      self.image_url
    end
  end

  # def price
  #   with_discount || super
  # end

  def with_discount
    (self.price - (self.price * (self.discount/100))).round(2)  if self.discount > 0 
  end

  def has_discount?
    self.discount > 0
  end

  def with_proper_picture
    {
      'id': self.id,
      'photo_url': picture_link
    }   
  end

  def custom_json
   
    response = { 
      'id': self.id,
      'title': self.title, 
      'description': self.description.gsub("\n",''),
        
      'price': nil,
      
      'photo_url': self.picture_link,
      'variants': 
    
     
        self.product_variants.map do |x| 
        { 'size': x.size.product_size,
          'color': Color.find(x.color_id).hex_value, 
          'quantity': x.quantity  
        }
        end
      
    }
    #byebug
    if self.has_discount?
      response[:price] = self.with_discount.to_f
      response[:discount_value] = self.discount.to_f
    else
      response[:price] = self.price.to_f
    end
    response
  end

end

# def custom_json
#   { 'title': self.title, 
#     'description': self.description.gsub("\n",''),
#     'price': self.price,
#   'variants': 
#   Size.all.map do |size|
#     product_variant = self.product_variants.where(product_id: self.id, size_id: size.id)
#     if !product_variant.blank?
#       { 'size': size.product_size,
#         'colors':
#         product_variant.map do |x| 
#           { 'color': Color.find(x.color_id).hex_value, 'quantity': x.quantity }
#         end
#       }
#     end
#   end.compact
#   }
# end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    # if params[:product][:photo_url].present?
    #   file = File.open(open(params[:product][:photo_url]).path)
    #   params[:product][:image] = file
    # end
    @product = Product.new(product_params)
    @product.build_with_category(params)
    #byebug
    if @product.save
      flash[:info] = 'New product created'
      redirect_to admin_products_path
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.build_with_category(params)
    if @product.update(product_params)
      flash[:info] = 'Product updated'
      redirect_to admin_products_path
    else
      render 'edit'
    end
    #byebug
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:info] = 'Product deleted'
    redirect_to admin_products_path
  end


  private

  def product_params
    params.require(:product).permit(:title, :price, :description, :brand_id, :photo_url, :image, :discount,
                                    product_variants_attributes: [ :id, :size_id, :color_id, :quantity, :_destroy ])
  end

end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApiController

  before_action :set_category, only: [:index, :show]

  def index
    params[:per_page] ||= 20
    if params[:page] || params[:per_page]
      @products = @category.products.select(:id, :photo_url).paginate(:page => params[:page], :per_page => params[:per_page])
      #byebug
    else
      @products = @category.products.select(:id, :photo_url)
    end
    render response: @products.map { |product| product.with_proper_picture }
  
  end


  def show_product
    
    @product = Product.find(params[:product_id])
    render response: @product.custom_json
  rescue ActiveRecord::RecordNotFound
    raise Api::Exceptions::RecordNotFound, 'Product'
    
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product

  def show
    product_variant = ProductVariant.where(product_id: @product)
    @size = product_variant.map { |product| product.size }.uniq
    @color = product_variant.map { |product| product.color }
    @cart_item = CartItem.new()
    @test_color = Hash.new { |k, v| k[v] = [] }
    product_variant.each do |product| 
      @test_color[Size.find(product.size_id).product_size] <<
        Color.find(product.color_id).product_color.strip 
    end
    #byebug                                                
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper

  def product_variant_quantity(f)
    if current_page? action: 'new'
      1
    else
      if f.object.quantity.blank?
        1
      else
        f.object.quantity
      end
    end  
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_admin_navbar_new_shoes.html.erb
<div class='row'>
	<div id='dashboard-title' class='col-md-10'>
		<ul class='list-inline'>
			<%= render 'admin/dashboard/navbar/links' %>
		</ul>
	</div>
	<div class='col-md-2'>
	  <%= link_to "DODAJ OBUCU", new_admin_product_path, class: 'btn create-new pull-right'  %>
	</div>
</div>

app/views/admin/products/_product_variant_fields.html.erb
<fieldset>
  <div class='col-md-4'>
    <div class='form-group'>
      <%= f.label :velicina %>
      <%= f.collection_select :size_id, Size.all, :id, :product_size, {}, { class: 'form-control' } %>
    </div>
  </div>
  <div class='col-md-4'>
    <div class='form-group'>
      <%= f.label :boja %>
      <%= f.collection_select :color_id, Color.all, :id, :product_color, {}, { class: 'form-control' } %>
    </div>
  </div>
  <div class='col-md-2'>
    <div class='form-group'>
      <%= f.label :kolicina %>
      <%= f.number_field :quantity,  { value: product_variant_quantity(f), min: 1, class: 'form-control' }  %>
    </div>
  </div>
  <div class='col-md-2'>
    <%= f.hidden_field :_destroy %>
    <%= link_to "<span class='glyphicon glyphicon-remove'></span>".html_safe, '#', class: 'remove_fields' %>
  </div>
</fieldset> 

app/views/admin/products/edit.html.erb
<% content_for :admin_navbar_new_shoes, render('admin/products/admin_navbar_new_shoes') %>
<div class='row' style='border: 1px solid #ECECEC; margin-bottom: 30px'>
  <div class='row' style='margin: 20px 45px 30px 30px'>
    <%= form_for @product, url: { controller: 'admin/products', action: 'update' },  multipart: true do |f| %>
    <div class='row'>
      <div class='col-md-6'>
        <% if @product.errors.any? %>
          <% @product.errors.full_messages.each do |message| %>
            <p style='font-size: 14px; color: #b30000'><%= message %></p>
          <% end %>
        <% end %>
        <div class="form-group">
          <%= f.label :naziv %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :opis %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class='row'>
          <div class='col-md-3'> 
            <div class="form-group">
              <%= f.label :cijena %>
              <%= f.number_field :price, min: 1, step: 'any', value: number_with_precision(f.object.price.round(2), precision: 2), class: 'form-control' %>
            </div>
          </div>
          <div class='col-md-3'> 
            <div class="form-group">
              <%= f.label :popust %>
              <%= f.number_field :discount, min: 0, max: 99, step: 'any', value: number_with_precision(f.object.discount.round(2), precision: 2), class: 'form-control' %>
            </div>
          </div>
        </div>
        <div id='product-category' class='row'>
          <div class='col-md-6'>
              <div class="form-group">
                <%= f.label :brend %>
                <%= f.select :brand_id, options_for_select( Brand.all.map { |b| [b.title, b.id ]}, Brand.find(f.object.brand_id).id ), {}, { class: 'selectpicker' } %>
              </div>  
          </div>
          <div class='col-md-6'>
            <div class="form-group">
              <%= label_tag :kategorija %>
              <%= select_tag :category_id, options_for_select( Category.all.map { |b| [b.title, b.id] }, f.object.categories.map {|category| category.id } ), { multiple: true, class: 'selectpicker'} %>
            </div>
          </div>
        </div>
        <div class='row' style='padding-right: 15px'>
          <%= f.fields_for :product_variants do |variant| %>
            <%= render 'product_variant_fields', f: variant %>
          <% end %>
          <%= link_to_add_product_variants 'DODAJ VARIJANTU', f, :product_variants %>
        </div>
      </div>
      <div class='col-md-6'>
        <div class='row'>
          <%= f.label :nil, 'Upload Slike' %>
          <% if @product.image.url.include? 'missing' %>
            <div class='col-md-12' style='padding: 0px'>
              <div class="fileUpload">
                <%= f.file_field :image, id: "uploadBtn", class: "upload" %>
                <div id='upload-button'>
                  <span class='glyphicon glyphicon-cloud-upload'></span>
                  <p>Uploaduj sliku</p>
                </div>
              </div>
              <input id="uploadFile" placeholder="No image selected" disabled="disabled" />
            </div>
          <% else %>
            <div class='col-md-12' style='padding: 0px'>
              <div class="fileUpload">
                <%= f.file_field :image, id: "uploadBtn", class: "upload" %>
                <div>
                  <%= image_tag @product.image.url(:medium), style: 'margin-top: 100px' %>
                </div>
              </div>
              <input id="uploadFile" placeholder="No image selected" disabled="disabled" />
            </div>
          <% end %>
        </div>
        <div class='row'>
          <div class="form-group">
            <%= f.label :nil, 'ili Link slike' %>
            <%= f.text_field :photo_url, class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>
    <div class='row' style='margin-top: 20px;'>
      <div class='col-md-4 col-md-offset-4'>
        <div class='col-md-10 col-md-offset-1'>
          <div class='pull-left'>
            <%= link_to 'ODUSTANI', admin_products_path, class: 'btn odustani' %>
          </div>
          <div class='form-group pull-left'>
            <%= f.submit 'IZMIJENI ARTIKAL', class: "btn create-new" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  document.getElementById("uploadBtn").onchange = function () {
  document.getElementById("uploadFile").value = this.value;
  };
</script>

app/views/admin/products/index.html.erb
<% content_for :admin_navbar_new_shoes, render('admin/products/admin_navbar_new_shoes') %>
<div class="row">
	<table class='table table-bordered table-hover'>
		<thead>
		  <tr>
		    <th>Naziv</th>
		    <th>Kategorija</th>
		    <th>Brand</th>
		    <th>Cijena</th>
		    <th style='text-align: center; width: 6%; padding-left: 0px !important'>Opcije</th>
		  </tr>
		</thead>
		<tbody>
		<% @products.each do |product| %>
		  <tr>
		    <td><%= product.title %></td>
		    <td><%= product.capitalize_category %></td>
		    <td><%= product.brand.title %></td>
		    <% if product.has_discount? %>
		    	<td><%= number_with_precision(product.with_discount, precision: 2) %><span style='color: red; font-size: 13px	'> D</span></td>
		    <% else %>
		    	<td><%= number_with_precision(product.price, precision: 2) %></td>
		    <% end %>
		    <td style='text-align: center; width: 6%; padding-left: 0px !important'>
		    	<%= link_to "<span class='glyphicon glyphicon-edit admin-icon'></span>".html_safe, 
		    		edit_admin_product_path(product), title: 'Edit product' %>
	        <%= link_to "<span class='glyphicon glyphicon-trash admin-icon'></span>".html_safe,            admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete product' %>
		    </td>
		  </tr>
		<% end %>
		</tbody>
	</table>
</div>

<script>
$(document).ready(function() {
    $('#dashboard-title').find('a').each(function() {
    if (this.href == window.location.href) {
        $(this).addClass('active-link')
        }
    });
});
</script>

app/views/admin/products/new.html.erb
<% content_for :admin_navbar_new_shoes, render('admin/products/admin_navbar_new_shoes') %>
<div class='row' style='border: 1px solid #ECECEC; margin-bottom: 30px'>
  <div class='row' style='margin: 20px 45px 30px 30px'>
    <%= form_for @product, url: { controller: 'admin/products', action: 'create' }, multipart: true do |f| %>
    <div class='row'>
      <div class='col-md-6'>
        <% if @product.errors.any? %>
          <% @product.errors.full_messages.each do |message| %>
            <p style='font-size: 14px; color: #b30000'><%= message %></p>
          <% end %>
        <% end %>
        <div class="form-group">
          <%= f.label :naziv %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :opis %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class='row'>
          <div class='col-md-3'> 
            <div class="form-group">
              <%= f.label :cijena %>
              <%= f.number_field :price, min: 1, step: 'any', class: 'form-control' %>
            </div>
          </div>
          <div class='col-md-3'> 
            <div id='discount'>
              <%= button_tag 'DODAJ POPUST', class: 'btn create-new', id: 'discount-button' %>
            </div>
          </div>
        </div>
        <div id='product-category'>
          <div class='row'>
            <div class='col-md-6'>
                <div class="form-group">
                  <%= f.label :brend %>
                  <%= f.select :brand_id, options_for_select( Brand.all.map { |b| [b.title, b.id ]}.unshift(['Izaberi brend',''])), {}, { class: 'selectpicker' } %>
                </div>  
            </div>
            <div class='col-md-6'>
              <%= link_to 'DODAJ BREND',  new_admin_brand_path, remote: true, class: 'btn create-new', id: 'new-brand' %>
            </div> 
          </div>  
          <div class='row'>
            <div class='col-md-6'>
              <div class="form-group">
                <%= label_tag :kategorija %>
                <%= select_tag :category_id, options_for_select( Category.all.map { |b| [b.title, b.id ]}), { multiple: true, class: 'selectpicker'} %>
              </div>  
            </div>
          </div>
        </div>
        <div class='row' style='padding-right: 15px'>
          <%= f.fields_for :product_variants do |variant| %>
            <%= render 'product_variant_fields', f: variant %>
          <% end %>
          <%= link_to_add_product_variants 'DODAJ VARIJANTU', f, :product_variants%>
        </div>
      </div>
      <div class='col-md-6'>
        <div class='row'>
          <%= f.label :nil, 'Upload Slike' %>
          <div class='col-md-12' style='padding: 0px'>
            <div class="fileUpload">
              <%= f.file_field :image, id: "uploadBtn", class: "upload" %>
              <div id='upload-button'>
                <span class='glyphicon glyphicon-cloud-upload'></span>
                <p>Uploaduj sliku</p>
              </div>
            </div>
            <input id="uploadFile" placeholder="No image selected" disabled="disabled" />
          </div>
        </div>
        <div class='row'>
          <div class="form-group">
            <%= f.label :nil, 'ili Link slike' %>
            <%= f.text_field :photo_url, class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>
    <div class='row' style='margin-top: 20px;'>
      <div class='col-md-4 col-md-offset-4'>
        <div class='col-md-10 col-md-offset-1'>
          <div class='pull-left'>
            <%= link_to 'ODUSTANI', admin_products_path, class: 'btn odustani' %>
          </div>
          <div class='form-group pull-left'>
            <%= f.submit 'KREIRAJ ARTIKAL', class: "btn create-new" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  document.getElementById("uploadBtn").onchange = function () {
  document.getElementById("uploadFile").value = this.value;
  };
</script>